# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [10.0.2.0/30]
      gateway4: 10.0.2.2
      nameservers:
              addresses: [10.0.2.3,8.8.8.8]
    enp0s8:
            dhcp4: no

