# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: yes
    enp0s8:
      dhcp4: no
      addresses: [192.168.1.56/30]
      nameservers:
              addresses: [8.8.8.8,8.8.4.4]
    enp0s9:
      dhcp4: yes
